In [1]:
#QUES1: Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T
print("\nTransposed Array (Rows and Columns Interchanged):")
print(transposed_arr)


Original Array:
[[ 86  84   1]
 [ 56  39   7]
 [100   1   2]]

Transposed Array (Rows and Columns Interchanged):
[[ 86  56 100]
 [ 84  39   1]
 [  1   7   2]]


In [2]:
#Ques2:Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
import numpy as np

# Generate a 1D array with 10 elements
arr = np.arange(1, 11)
print("Original 1D Array:")
print(arr)

# Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(arr_2x5)

# Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped into 2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped into 5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [3]:
#Ques3: Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Create a 4x4 array with random float values between 0 and 1
arr = np.random.random((4, 4))
print("Original 4x4 Array:")
print(arr)

# Add a border of zeros around the array, resulting in a 6x6 array
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(arr_with_border)


Original 4x4 Array:
[[0.29453086 0.39342848 0.25531816 0.0564752 ]
 [0.28005202 0.81462318 0.33876838 0.23270514]
 [0.24572668 0.22350886 0.71042681 0.8022362 ]
 [0.09321324 0.59940346 0.06198024 0.36485345]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.29453086 0.39342848 0.25531816 0.0564752  0.        ]
 [0.         0.28005202 0.81462318 0.33876838 0.23270514 0.        ]
 [0.         0.24572668 0.22350886 0.71042681 0.8022362  0.        ]
 [0.         0.09321324 0.59940346 0.06198024 0.36485345 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
#Ques4:Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
#Ques5:. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)  # Convert to uppercase
lowercase_arr = np.char.lower(arr)  # Convert to lowercase
titlecase_arr = np.char.title(arr)  # Convert to title case

# Print the results
print("Original Array:")
print(arr)
print("\nUppercase Array:")
print(uppercase_arr)
print("\nLowercase Array:")
print(lowercase_arr)
print("\nTitlecase Array:")
print(titlecase_arr)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']


In [ ]:
#Ques6:Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
arr_with_spaces = np.char.join(' ', arr)

# Print the result
print(arr_with_spaces)


['p y t h o n' 'n u m p y' 'p a n d a s']


In [7]:
#Ques7:Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Element-wise addition
addition_result = arr1 + arr2

# Element-wise subtraction
subtraction_result = arr1 - arr2

# Element-wise multiplication
multiplication_result = arr1 * arr2

# Element-wise division
division_result = arr1 / arr2

# Print the results
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)

print("\nElement-wise Division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise Addition:
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
[[ 6 10 12]
 [12 10  6]]

Element-wise Division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


In [8]:
#Ques8:Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [9]:
#Ques9:Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array\
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, 100)

# Find the prime numbers in the array
prime_numbers = [num for num in arr if is_prime(num)]

# Display the array and the prime numbers
print("Array of 100 random integers:")
print(arr)

print("\nPrime numbers in the array:")
print(prime_numbers)


Array of 100 random integers:
[559 808 708 687 501  39  67 978 922 244 340 499 904 454 650 578  15 236
 253 706 741 995 209 689 853 998 351 291 230 396 387 726 973 134  10 333
 580 924 244 253 142 460 700 105 463 243 977 156 405 859 210 897 351 849
  25 974  10 990 182 840 236 559 867 253 705 304 747 434 933 665  38  24
  99 816 165 990 224 911 749 486 338 204 535 896 314 880 179 469 740 246
 506 795 917 204 979 565 752 691 320 504]

Prime numbers in the array:
[np.int32(67), np.int32(499), np.int32(853), np.int32(463), np.int32(977), np.int32(859), np.int32(911), np.int32(179), np.int32(691)]


In [ ]:
#Ques10:Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(15, 35, size=30)  # Random temperatures between 15°C and 35°C

# Reshape the array into 5 weeks (5 rows, 6 columns) and calculate weekly averages
weekly_averages = daily_temperatures.reshape(5, 6).mean(axis=1)

# Display the daily temperatures and weekly averages
print("Daily Temperatures for the Month:")
print(daily_temperatures)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for the Month:
[24 25 29 18 28 23 26 19 33 19 30 17 18 30 29 17 28 21 31 15 32 17 21 29
 32 21 18 22 21 31]

Weekly Averages:
[24.5        24.         23.83333333 24.16666667 24.16666667]
